# Generated by Django 4.0.4 on 2022-09-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('Bio', models.TextField()),
                ('imagem', models.URLField()),
                ('link', models.URLField()),
                ('nome', models.CharField(max_length=140)),
            ],
        ),
    ]
