# Generated by Django 4.0.4 on 2022-09-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pytech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='guid',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
